<?xml version="1.0" encoding="ASCII"?>
<compare:Comparison xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:compare="http://www.eclipse.org/emf/compare">
  <matchedResources leftURI="platform:/resource/testSpring/springToDedal.ecore"/>
  <matchedResources rightURI="platform:/resource/testSpring/springToDedal2.ecore"/>
  <matches>
    <submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_5dMWByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_5dMWByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_5dMmByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_5dMmByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_5dM2ByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_5dM2ByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_5dNGByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_5dNGByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_5dNWByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_5dNWByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <differences xsi:type="compare:ReferenceChange" requires="//@matches.0/@submatches.0/@differences.0" kind="CHANGE">
          <reference href="http://www.dedal.fr/metamodel#//InstConnection/clientInstElem"/>
          <value href="platform:/resource/testSpring/springToDedal.ecore#_b_5dNGByEemLVLU7xrrk4w"/>
        </differences>
        <differences xsi:type="compare:ReferenceChange" requires="//@matches.0/@submatches.0/@differences.0" kind="CHANGE">
          <reference href="http://www.dedal.fr/metamodel#//InstConnection/serverInstElem"/>
          <value href="platform:/resource/testSpring/springToDedal.ecore#_b_5dMmByEemLVLU7xrrk4w"/>
        </differences>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_vAGmAGDmEemLVLU7xrrk4w"/>
      </submatches>
      <differences xsi:type="compare:ReferenceChange" requiredBy="//@matches.0/@submatches.0/@submatches.5/@differences.0 //@matches.0/@submatches.0/@submatches.5/@differences.1">
        <reference href="http://www.dedal.fr/metamodel#//Assembly/assemblyConnections"/>
        <value href="platform:/resource/testSpring/springToDedal.ecore#_vAGmAGDmEemLVLU7xrrk4w"/>
      </differences>
      <left href="platform:/resource/testSpring/springToDedal.ecore#//@architectureDescriptions[name='SpringModel%20-%20http%3A%2F%2Fwww.xtext.org%2Fspring%2FSpringConfigDslAssembly']"/>
      <right href="platform:/resource/testSpring/springToDedal2.ecore#//@architectureDescriptions[name='SpringModel%20-%20http%3A%2F%2Fwww.xtext.org%2Fspring%2FSpringConfigDslAssembly']"/>
    </submatches>
    <submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_4PEGByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_4PEGByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_42IGByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_42IGByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_42IWByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_42IWByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_42ImByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_42ImByEemLVLU7xrrk4w"/>
      </submatches>
      <submatches>
        <left href="platform:/resource/testSpring/springToDedal.ecore#_b_5dMGByEemLVLU7xrrk4w"/>
        <right href="platform:/resource/testSpring/springToDedal2.ecore#_b_5dMGByEemLVLU7xrrk4w"/>
      </submatches>
      <left href="platform:/resource/testSpring/springToDedal.ecore#//@architectureDescriptions[name='SpringModel%20-%20http%3A%2F%2Fwww.xtext.org%2Fspring%2FSpringConfigDslConfiguration']"/>
      <right href="platform:/resource/testSpring/springToDedal2.ecore#//@architectureDescriptions[name='SpringModel%20-%20http%3A%2F%2Fwww.xtext.org%2Fspring%2FSpringConfigDslConfiguration']"/>
    </submatches>
    <left href="platform:/resource/testSpring/springToDedal.ecore#/"/>
    <right href="platform:/resource/testSpring/springToDedal2.ecore#/"/>
  </matches>
</compare:Comparison>
